### ISSUE TITLE
你好，我用了JMUI框架，类名样式没办法应用上

### ISSUE THREAD

**Issue by TinkerDeng** [hahoocn/react-mobile-boilerplate#10]
直接 import { Button } from 'jmui';  ，样式发现是标签样式 都应用上了 但是以类名开始的样式都没应用上
	<Button>aaa</Button>，我想问一下这个怎么解决，我发现 只要不是 const Style = require('./index.css'); 以  <div className={Style.xxxx}></div>明明的样式 都打包不进 webpack-assets.json这个文件

**Comment by ihahoo** [comment]
为了服务器端渲染同构，用了[webpack-isomorphic-tools](https://github.com/halt-hammerzeit/webpack-isomorphic-tools)，做了一些设置，可能在引用css的时候要用require。另外在css这块，主要用了[css-modules](https://github.com/css-modules/css-modules)和[postcss](http://postcss.org/)，是可以替代sass和less的，主要就是一个组件和这个组件的css可以放到一起，而且名称不用怕合并的时候混淆，我在webpack里有做了设置，合并一个css的时候会增加一些名称。比如我这个组件里https://github.com/hahoocn/hahoo-admin/tree/master/src/components/hahoo/Dialog 把css和js放到一起，并且js里引用了这个css后，直接可以用css里定义的名称调用样式，然后其它工作，webpack和postcss loader等相关loader来打包处理，这样做就是模块化，css modules的概念也是css模块化。jmui我不是很了解，你是用的这个[jmui](https://github.com/choujimmy/jmui)吗？我看它用的是less，而现在的项目里没有组合less，你可以安装less并配置webpack css load加上less试试。

比如先安装webpack的less loader，然后配置
```javascript
    {
        test: /\.less$/,
        loader: 'style!css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss!less'
      },
```
