### ISSUE TITLE
404 when I visit the website through localhost

### ISSUE THREAD

**Issue by YuxinChou** [hahoocn/react-mobile-boilerplate#7]
bulid with 'npm run build:client'

Mac OS, username/Sites/build.. 
local server

http://localhost/build/

> 404
> This is not the web page you are looking for.

when start with 'npm run start', everything is right.

thankyou.

**Comment by ihahoo** [comment]
npm run build:client: only packaged the browser client used files.
Including html, packed js, css, images...
It does not contain a server environment.

Sometimes we just want to use the packaged file , don't want to use server-side rendering, you can use this command to generate a package file to the /build/ folder, you can then move it and use a different web server publishing it.

npm run build: packaged static resources to the /public/ folder.
npm run start: start express server and includes the static folder /public/, now you can use server-side rendering.
